# Generated by Django 2.2 on 2020-01-23 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=300, verbose_name='Полное наименование')),
                ('short_name', models.CharField(db_index=True, max_length=300, verbose_name='Краткое наименование')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('inn', models.DecimalField(decimal_places=0, max_digits=13, verbose_name='ИНН')),
                ('license_adress', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('adress', models.TextField(verbose_name='Фактический дарес с индексом')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(db_index=True, max_length=100, verbose_name='Email')),
                ('site', models.CharField(db_index=True, max_length=100, verbose_name='Сайт')),
                ('license_date', models.DateField(verbose_name='Срок действия лицензионного сертификта')),
                ('license_upload', models.FileField(upload_to='upload/', verbose_name='Лицензия')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователя',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_status', models.IntegerField(choices=[(0, 'проект'), (1, 'в работе'), (2, 'окончен')], default=0, verbose_name='Статус проекта')),
                ('neocom_status', models.IntegerField(choices=[(0, 'на расмотрении'), (1, 'одобрен'), (2, 'не одобрен')], default=0, verbose_name='Статус Neocom')),
                ('project_name', models.CharField(db_index=True, max_length=300, verbose_name='Название проекта')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('inn', models.DecimalField(decimal_places=0, max_digits=13, verbose_name='ИНН')),
                ('end_customer', models.CharField(default='', max_length=300, verbose_name='Конечный заказчик')),
                ('probability', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Вероятность реализации')),
                ('contacts', models.TextField(blank=True, verbose_name='контактные данные')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(blank=True, verbose_name='Дата окончания проекта')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Profile')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=15, verbose_name='код')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Активность')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='projects.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='projects.Product', verbose_name='Продукт')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиция',
            },
        ),
    ]
