# Generated by Django 2.2 on 2020-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, verbose_name='ИНН'),
        ),
    ]
