# Generated by Django 2.2 on 2020-01-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200123_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=13, verbose_name='ИНН'),
        ),
    ]
